### ISSUE TITLE
L2Basket and L5Basket are not appearing in the 3D view

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/HNN-UI#55]
L2Basket and L5Basket are overlapping in the 3D model

**Comment by tarelli** [comment]
Both layers are superposed as they occupy the same space in the model. They are also both hidden by the pyramidal cells. @salvadord is investigating.

**Comment by tarelli** [comment]
Correction: they are not both hidden, there is a bit that is visible, see screenshot. L2Basket though are still covered by L5Basket (yellow in the screenshot) so that bit still needs to be fixed.
<img width="1761" alt="Screenshot 2019-07-30 at 11 36 01" src="https://user-images.githubusercontent.com/81127/62122765-60425100-b2be-11e9-9b44-533fb099ce0e.png">

**Comment by salvadord** [comment]
ok, so fixed 2 issues and commited to the hnn repo: https://github.com/jonescompneurolab/hnn/tree/netpyne

The issues fix the y location of L5Basket cells so they are not on top of L2Basket; and fix an incorrect offset that the L2Pyr pt3d cells had in the x-axis.

The figure below shows how the representation should look in HNN. The L2Basket and L5Basket cells are still on top of the pyramidal cells. Actually, the L2Basket are slightly above. This is how the original HNN model looked too -- see https://raw.githubusercontent.com/jonescompneurolab/hnn-tutorials/master/Tour%20of%20the%20GUI/images/image24.png. In that figure the Pyramidal cell somas are not show, and that's the only reason you can see the Basket cells. 

These locations cannot be changed because it would affect the connectivity. They could be temporarily moved to a different location just to get a figure.
 
![image](https://user-images.githubusercontent.com/8440562/62164914-43704280-b2eb-11e9-81a8-ff9188f51f72.png)

**Comment by salvadord** [comment]
I did not have to run the defineShapes function to get the Basket cells. Not sure why this is required in HNN-UI -- perhaps it's related to how you create the network etc

**Comment by salvadord** [comment]
I generated these figures by temporarily modifying the y location of the Basket populations -- I'll share with Dylan, in case he wants to use
![image](https://user-images.githubusercontent.com/8440562/62166946-0a869c80-b2f0-11e9-9116-f45e7be68242.png)
![image](https://user-images.githubusercontent.com/8440562/62167021-3bff6800-b2f0-11e9-8ca8-5f6104449d9e.png)
![image](https://user-images.githubusercontent.com/8440562/62167032-46216680-b2f0-11e9-8e33-549047b47d82.png)
![image](https://user-images.githubusercontent.com/8440562/62167055-56d1dc80-b2f0-11e9-8bd8-c3b8fd0763c3.png)
![image](https://user-images.githubusercontent.com/8440562/62167168-9c8ea500-b2f0-11e9-882e-f5f9cbf44a75.png)
![image](https://user-images.githubusercontent.com/8440562/62167235-c6e06280-b2f0-11e9-92e7-3a4f49f0ca62.png)
![image](https://user-images.githubusercontent.com/8440562/62167304-e7a8b800-b2f0-11e9-8bbe-b0caa78437da.png)
![image](https://user-images.githubusercontent.com/8440562/62167334-fee7a580-b2f0-11e9-9325-d5f93917e2b3.png)

**Comment by salvadord** [comment]
Can also get pics with wider distribution:

![image](https://user-images.githubusercontent.com/8440562/62167791-f9d72600-b2f1-11e9-9cf3-90a4d3443794.png)
![image](https://user-images.githubusercontent.com/8440562/62167854-183d2180-b2f2-11e9-910a-a9b97d17fbbd.png)
